### ISSUE TITLE
Multiplayer Crash

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Tim020/Tiny-Storage#24]
Less dis-organized

https://gist.github.com/DPxKnightxZero/e71110ebd94cfa85c4a5

**Comment by Tim020** [comment]
I'll look into this at the weekend - have a couple of uni assessments due this week! Thanks for reporting :)

**Comment by marchermans** [comment]
I found the issue and wil take a look at It this weekend. Hopefully i can fix It by applying a SideOnly, but that does not look like It.

**Comment by marchermans** [comment]
Or not this weekend, i mean tomorrow

**Comment by Tim020** [comment]
I'm trying to figure out why its crashing, seen as the packet is handled client side! Also, I can't find a reference to the MP entity anywhere that would cause the error

**Comment by Tim020** [comment]
I should also be around tomorrow afternoon/evening, so can take a look with you then!

**Comment by P3rf3ctXZer0** [comment]
This is a crash caused server side only if that helps.

**Comment by marchermans** [comment]
Sadly i was also able reproduce on the integrated server. It has todo width the way Tim stores the global friends list (on the entity) an the way he synchronizes it from the server to the client (on and the same class) due to that fact and the fact that a Instance of EntityClientMP (the server side instance of a EntityPlayer) does not exist on the client side when connecting to a dedicated server, causing the issue.

I tried simply applying a SideOnly(Side.Server) but the import to that class stays, making the class loader still look for that class which simply does not exist on the Client side. Tim has to pull the synchronization stuff out of that class to fix it.

**Comment by marchermans** [comment]
Sorry for the weird typos, my phone does stupid stuff. 😁

**Comment by Tim020** [comment]
I've changed the active version on the curseforge site to be the one that doesn't have this issue - when I'm home and on my laptop I'll roll back the master branch on here to reflect this

**Comment by Tim020** [comment]
Update on this issue: seems like I'm going to need to re-write the system that handles storing the Global Friends list. This shouldn't take too long, but I have 2 uni assessments due this week... Hopefully I'll get a new version up by Friday though :)
